version: '3'
services:
  db:
    #image: mysql:5.7
    build:
      context: ./mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafio_nginx_node_mysql
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-nginx-node-network
    # substitui o dockerize
    healthcheck:
      #test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 10s
      retries: 3

  app:
    build:
      context: ./node
    container_name: app
    entrypoint: sh -c "npm install && node index.js"
    #entrypoint: sh -c "npm install && node index.js && dockerize -wait tcp://db:3306 -timeout 10s node index.js"
    tty: true
    networks:
      - desafio-nginx-node-network
    volumes:
      - ./node:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - desafio-nginx-node-network
    depends_on:
      - app

networks:
  desafio-nginx-node-network:
    driver: bridge