version: '3.9'
services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafio-nginx-node-db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-nginx-node-network

  app:
    build:
      context: ./app
      #dockerfile: ./app/Dockerfile
    container_name: app
    #volumes:
    #  - ./app:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - desafio-nginx-node-network
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      #dockerfile: ./nginx/Dockerfile
    container_name: nginx
    #volumes:
      #- ./nginx/nginx.conf:/etc/nginx/conf.d
    networks:
      - desafio-nginx-node-network
    depends_on:
      - app

networks:
  desafio-nginx-node-network:
    driver: bridge