version: '3'
services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafio-nginx-node-db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-nginx-node-network

  app:
    build:
      context: ./app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 10s node index.js
    networks:
      - desafio-nginx-node-network
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - desafio-nginx-node-network
    depends_on:
      - app

networks:
  desafio-nginx-node-network:
    driver: bridge