version: '3.9'
services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafio-nginx-node-db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-nginx-node-network

  nodeserver:
    build:
      context: ./app
    container_name: app
    ports:
      - "3000:3000"
    networks:
      - desafio-nginx-node-network
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - desafio-nginx-node-network
    depends_on:
      - nodeserver

networks:
  desafio-nginx-node-network:
    driver: bridge